server:
  #配置端口
  port: 8080

#数据库配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/esports?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8

#mybatis配置
mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      example:
        mapper:
          debug

#pagehelper
  pagehelper:
    helperDialect: mysql
    reasonable: true